### ISSUE TITLE
Tri ascendant/descendant des données

### ISSUE THREAD

**Issue by ygibon** [cbib/Plato#10]
même problème que dans excel quand les chiffres sont au format texte: on a des trucs du style 4230>413>4002...

**Comment by ebouilhol** [comment]
Merci yves,

Aurais-tu en mémoire dans quelles pages cela se produit ?

**Comment by ygibon** [comment]
Dans la table “export”

 

De : ebouilhol [mailto:notifications@github.com] 
Envoyé : lundi 3 octobre 2016 09:47
À : cbib/Plato
Cc : ygibon; Author
Objet : Re: [cbib/Plato] Tri ascendant/descendant des données (#10)

 

Merci yves,

Aurais-tu en mémoire dans quelles pages cela se produit ?

**Comment by ebouilhol** [comment]
Le seul moyen de regler ce souci est de changer les "NA" de la table d'export par des NaN (qui sont considérés comme des nombres et permettent le tri sur les nombres)
