### ISSUE TITLE
Mise en forme réinitialisée à chaque édition: pénible

### ISSUE THREAD

**Issue by ygibon** [cbib/Plato#11]
Quand j'édite un standard ou analyte, je le choisis dans la liste après avoir trié par exemple d'après le code et viré des colonnes qui me semblaient inutiles, je clique sur le symbole de crayon, le pop up s'affiche, c'est cool. Mais quand je ferme, la liste s'affiche à nouveau en mode défaut. C'est pénible car il faut re-trier, etc.
Y a pas moyen de rester sur le mode d'affichage de la liste tel qu'il était en dernier?

**Comment by ebouilhol** [comment]
Problème résolu dans les deux pages que tu as cité, est-ce que tu veux que je généralise cela à toutes les tables ?

**Comment by ygibon** [comment]
Ben oui 

A+

y

 

De : ebouilhol [mailto:notifications@github.com] 
Envoyé : lundi 3 octobre 2016 09:56
À : cbib/Plato
Cc : ygibon; Author
Objet : Re: [cbib/Plato] Mise en forme réinitialisée à chaque édition: pénible (#11)

 

Problème résolu dans les deux pages que tu as cité, est-ce que tu veux que je généralise cela à toutes les tables ?

**Comment by ebouilhol** [comment]
Résolu
