### ISSUE TITLE
Troubles with trash

### ISSUE THREAD

**Issue by Cabasson** [cbib/Plato#12]
Hello
En labdesigner j'ai créé un batches "franklin_master 5".
J'avais un doublon dans mon fichier d'origine, détecté. Je soumets tout de même.
1er bug) Ce batch est tout de même accepté. Il sera appelé "0...." visible uniquement par labadmin.

En labadmin, je supprime ce batch. Je vérifie qu'il est bien supprimé (pas dans le menu déroulant)
Je crée un nouveau batch.
2° bug) Un message me dit que ce nom existe.
Je créer un batch avec un nom différent. 
3° bug) Je ne peux pas copier les noms car un message me dit qu'ils sont déjà utilisés alors que je vérifie que non en labadmin.

Merci. C'est assez urgent, des partenaires attendent leurs données.
Cécile
--

**Comment by ebouilhol** [comment]
Souci normalement réglé avec la nouvelle release.
