### ISSUE TITLE
Troubles with standard

### ISSUE THREAD

**Issue by Cabasson** [cbib/Plato#13]
Dans Std_Tomato_GreenF_2016-1-1, j'ai bien enregistré (avec l'ancien Plato) les valeurs du standard pour l'amidon et les protéines.
1er bug) Or ces deux métabolites n'apparaissent pas dans le menu déroulant quand je fais "raw processing" pour l'expérimentation 	"Tomato_ILS_GreenFruit_2015_Franklin"
En labadmin j'ai supprimé puis réédité ces deux métabolites. Cela n'arrange rien.
J'ai pensé à réactualisé la page à chaque fois avant de consulter le menu déroulant.

Merci de corriger aussi rapidement que possible ce bug toujours pour notre partenaire Franklin en attente de ces résultats.
Bien sincèrement
Cécile

**Comment by ebouilhol** [comment]
Merci pour le retour, 
je commence a investiguer.

**Comment by ygibon** [comment]
On constate que le tartrate apparait dans les analytes au choix pour ces batches. Or le tartrate n'a jamais été dosé ni déclaré pour les fruits de tomate (n'existe que dans le raisin). Du coup, je me demande si il n'y aurait pas un problème d'index automatique? En effet j'ai édité les identifiant des métabolites (j'ai simplifié leurs codes): du coup je me demande si ça n'a pas changé leur index et du coup foutu le bordel?

**Comment by ebouilhol** [comment]
Bonjour,
le problème est réglé pour cette experiment.

Le souci vient du fait que dans l'ancien Plato, le standard "Std_Tomato_GreenF_2016" est le contrôle de l'experiment "VitisREF". 

"Tomato_ILS_GreenFruit_2015_Franklin" dans l'ancien Plato n'a pas de standard.

De ce fait, le standard associé a l'experiment  "Tomato_ILS_GreenFruit_2015_Franklin" dans le nouveau plato n'etait pas "Std_Tomato_GreenF_2016" mais "VitisREF". 
Donc il aurait fallu modifier Starch et Protein dans VitisREF...

J'ai effectué le transfert manuellement vers "Std_Tomato_GreenF_2016". Pour cette experiment ça doit remarcher.

Le problème soulevé est peut-être plus important qu'il n'en a l'air, je vais creuser plus loin.

En attendant si vous re-rencontrez ce genre d'ennuis, n'hesitez pas a me le signaler
