### ISSUE TITLE
Aliquots fraichement enregistrés pas visibles de suite

### ISSUE THREAD

**Issue by ygibon** [cbib/Plato#14]
J'ai rentré des aliquots numérotés de 101 à 124 pour Std_Tomato_GreenF_2016. Tout a eu l'air de bien se passer, sauf que je n'ai pas vu les aliquots apparaitre dans la table une fois l'opération terminée. Ce n'est qu'en revenant voir plus tard 'parès avoir changé de panel) que j'ai retrouvé les aliquots. Bref, c'est pas top car l'utilisateur risque de croire que ça ne marche pas et s'acharner...

**Comment by ebouilhol** [comment]
Je fais des test pour voir ce qui s'est passé, jusque la je ne suis pas retombé sur ce soucis même avec plusieurs centaines d'aliquots. Si le problème se reproduit n'hésite pas a me dire sur quelle experience.
