### ISSUE TITLE
only one control is allowed ???

### ISSUE THREAD

**Issue by ygibon** [cbib/Plato#15]
je copie-paste une table pour créer un batch et je vois ce message apparaitre ("only one control is allowed"). WTF? Bref je me dis que j'ai merdé. je reviens 1 min plus tard et constate que la table a fini par être copiée. Sans doute la lenteur, mais le message d'erreur risque de provoquer des problèmes avec l'utilisateur non-averti.

**Comment by ebouilhol** [comment]
Plato ne gère pas le fait d'avoir deux standards différents. C'est ce qui avait provoqué le souci rencontré par Maria la semaine dernière. Depuis j'affiche quand deux contrôles sont entrés.

Le fait que cela s'affiche dans ce cas devait provenir du fait que certains noms d'experiment avaient gardé leur espace dans le nom et d'autres non.
