### ISSUE TITLE
Create batch non fonctionnel

### ISSUE THREAD

**Issue by ygibon** [cbib/Plato#16]
La première case reste obstinément en surbrillance orange et le message d'erreur "Some freshweights are already used or not created" s'affiche. Pourtant le sample est déclaré correctement dans l'onglet aliquots. La tentative de le remplacer par un "?" échoue aussi. Bref Plato refuse la création d'un nouveau batch.

**Comment by ebouilhol** [comment]
Je viens de consulter les fichiers en question. Cela vient du fait que l’expérience a été crée avec des espaces dans le nom. Par la suite lors de la création du batch, plato va chercher dans la base de données un nom avec un espace. Hors sur la première case le logiciel ne prend pas en compte le premier espace. De ce fait seule la première case était en surbrillance.

Pour éviter ce genre de soucis j'enlève désormais tous les espaces dans les noms.

Cela devrait marcher maintenant. Ayant les fichiers en ma possession je vais recréer l’expérience.
