### ISSUE TITLE
create batch non fonctionnel, suite

### ISSUE THREAD

**Issue by ygibon** [cbib/Plato#17]
on constate aussi que les aliquots du standard utilisé ne sont pas reconnues.

**Comment by ebouilhol** [comment]
Ils sont reconnus mais affichés comme déjà utilisés car ils sont utilisés dans les batchs suivant : 
(pour les standards de 1 a 11)
Tomato_Microtom_Tsukuba_2016_Exp1
Tomato_Microtom_Tsukuba_2016_Setup
