### ISSUE TITLE
Batches pas enregistrés

### ISSUE THREAD

**Issue by ygibon** [cbib/Plato#18]
Bien vu l'espace au début de l'ID :-)
Du coup, on arrive à tout rentrer (samples et standards);  ça met des plombes! On pense enfin avoir enregistré et puis plus rien: le batch n'apparait nulle part ("select batch" dans onglet batches ou raw data processing). Par contre, quand on essaye de le refaire le système dit qu'il existe déjà. 
La manipe en question est toujours "Tomato_ILS_GreenFruit_2015_Franklin(V2)"

**Comment by ebouilhol** [comment]
Je soupçonne que ce souci (que je n'arrive pas a reproduire) provienne des effets de bords qu'ont du apporter les contrôles que j'ai rajouté sur les espaces dans les noms. 
Les batches en question apparaissent quand on regarde dans l’expérience associée au standard (le standard, pour simplifier) Std_Tomato_GreenF_2016. En effet tout les aliquots autre que le standard n'ont pas été pris en compte, surement a cause de cette histoire d'espace en plus ou en moins.

En gros, l'espace en trop n'a pas gêné lors du controle du plan de plaque, car le logiciel l'a viré. Par contre a l'insertion du plan de plaque cela a posé problème car la base de donnée n'a pas reconnue l'experience. 

Je pense que si on recommence de zero cette manip   "Tomato_ILS_GreenFruit_2015_Franklin(V2)"
tout devrait fonctionner.

Je pourrais le faire avec les fichiers de Cécile, mais il y a certains samples sur Std_Tomato_GreenF_2016 qui sont déjà utilisés dans la base, par d'autres batches, ce qui empêche l'ajout des premier plan de plaque.

Les  Std_Tomato_GreenF_2016 aliquots 1 a 11 sont utilisés par les batch : 
Tomato_Microtom_Tsukuba_2016_Exp1
Tomato_Microtom_Tsukuba_2016_Setup

C'était déjà comme ça dans l'ancien Plato, cela a été transporté dans le nouveau. N'hésites pas à me dire comment vous voulez régler ça si vous souhaitez que je rentre cette manip

**Comment by ygibon** [comment]
Oui j'avais vu que ces standards étaient pris par Masaru (Tsukuba...): il les a rentrés entre temps. Il ne savait pas qu'ils étaient déjà utilisés. Bref c'est pour ça que j'ai rentré ces standards affublés des ID 101 à 124. Du coup tout semblait marcher nickel mais à la fin, rien.

**Comment by ebouilhol** [comment]
Bonjour,

J'ai utilisé ces nouveaux aliquots que tu as crées pour rentrer l'experiment avec les données que Cécile m'a envoyé. 
Tomato_ILS_GreenFruit_2015_Franklin
Les 4 plan de plaque envoyés sont entrés ainsi que les valeurs pour le starch.
