### ISSUE TITLE
Export/Visualization

### ISSUE THREAD

**Issue by Cabasson** [cbib/Plato#19]
Bonjour Emmanuel

Tout va très bien avec PLATO. Merci beaucoup pour ton assistance. Les résultats sont prêts.
Toutefois encore une remarque concernant la fonction "Export"
1) On choisit l'onglet "Normal" : Normal devient transparent et un tableau s'affiche
2) On choisit l'onglet "Aliquot merge" : Aliquot merge + Normal deviennent transparent et le tableau s'affiche (on peu voir qu'il n'y a plus la colonne aliquot)
3) On choisit "Batching center" : Batching center + Aliquot merge + normal deviennent transparent. Une barre de progression s'affiche et ça peut être très long. On ne sait pas si le tableau est affiché. En fait il ne l'est pas en général.  j'ai fait l'erreur d'exporter des tableaux en croyant que cette troisième option avait été choisie alors qu'il n'en était rien.

La meilleure option :
Il faut à partir du normal cliquer directement batch centering pour obtenir le bon tableau (enfin j'espère) et les trois onglets deviennent  transparents.

Il manque peut être un message intermédiaire.

Bien cordialement,
CC

**Comment by ebouilhol** [comment]
Bonjour Cécile,

Merci pour le retour. La barre de progression quand on clique sur "interbatch centering" est parfois longue a s'afficher, je vais essayer de régler ça.

Pour être sur d'avoir bien compris le problème : 
- La sélection des boutons n'est pas très claire ?
- Parfois le résultat ne s'affiche pas ?

Enfait on peut utiliser l'aliquot merge après l'interbatch centering, mais pas l'inverse (faire un interbatch centering après un aliquot merge)

Amicalement,

Emmanuel

**Comment by Cabasson** [comment]
[https://personnels.u-bordeaux.fr/bundles/nubcore/images/logo/logo_fr.svg][http://www6.bordeaux-aquitaine.inra.fr/var/internet_bordeaux_bfp/storage/images/_aliases/inra_logo/setup2/configuration/haut-de-page/logo-principal/34525-3-fre-FR/Logo-Principal.png]


Dr Cécile CABASSON
Maître de conférences
Veuillez noter mon nouveau courriel cecile.cabasson@inra.fr
+33(0)5 57 12 25 56
-----------------------------------
Centre INRA Bordeaux
71, avenue Edouard Bourlaux, CS 20 032
33882 Villenave d'Ornon Cedex
France
Web : Université de Bordeaux<http://www.u-bordeaux.fr/Formation/Composantes-de-formation/IUT-de-l-universite-de-Bordeaux/IUT-site-de-Perigueux>
Web : U<http://www6.bordeaux-aquitaine.inra.fr/bfp>MR Biologie du Fruit et Pathologie<http://www6.bordeaux-aquitaine.inra.fr/bfp>
Web : Plateforme Métabolome<http://www.cgfb.u-bordeaux2.fr/en/metabolome>
________________________________
De : ebouilhol <notifications@github.com>
Envoyé : mercredi 9 novembre 2016 13:48
À : cbib/Plato
Cc : Cecile Cabasson; Author
Objet : Re: [cbib/Plato] Export/Visualization (#19)


Bonjour Cécile,

Merci pour le retour. La barre de progression quand on clique sur "interbatch centering" est parfois longue a s'afficher, je vais essayer de régler ça. Oui effectivement, c'est très long

Pour être sur d'avoir bien compris le problème :

  *   La sélection des boutons n'est pas très claire ? C'est ça
  *   Parfois le résultat ne s'affiche pas ? On n'en est pas assuré

Enfait on peut utiliser l'aliquot merge après l'interbatch centering, mais pas l'inverse (faire un interbatch centering après un aliquot merge) - Je le découvre Il faut peut-être inversé les deux onglets ?

Amicalement,

Emmanuel

-

**Comment by ebouilhol** [comment]
Bonjour Cécile,

As-tu de nouvelles infos sur ce que tu avais soulevé plus haut ?

Amicalement,

Emmanuel

**Comment by Cabasson** [comment]
Bonjour Emmanuel


Nous avons changé de messagerie avec l'INRA au plan national et je n'ai pas encore accès à toutes les fonctionnalités (faute de temps pour m'en occuper).

Je n'ai pas accès à "ce que j'ai soulevé plus haut"...


Pour ma part, je l'ai transmis à Yves, tout a très bien fonctionné la dernière fois. Il est vrai que c'est toi qui a fait les premières saisies au final.

En revanche, j'ai complété les autres métabolites et j'ai réussi à générer les tables.

Il y avait une question d'affichage  concernant l'export.

Je viens de faire un tour sur PLATO. Si on clique sur l'export des paramètres stat, tout se grise.

Si on clique sur 'batch centering', 'std' se grise indiquant qu' on n'y a plus accès en revanche on peut encore faire de l'aliquot merge'. Ça a l'air pas mal comme cela, en tout cas de mon point de vue.


J'espère avoir répondu à ta demande.
Bonne journée



[https://personnels.u-bordeaux.fr/bundles/nubcore/images/logo/logo_fr.svg][http://www6.bordeaux-aquitaine.inra.fr/var/internet_bordeaux_bfp/storage/images/_aliases/inra_logo/setup2/configuration/haut-de-page/logo-principal/34525-3-fre-FR/Logo-Principal.png]

.

Dr Cécile CABASSON
Maître de conférences
Veuillez noter mon nouveau courriel cecile.cabasson@inra.fr
+33(0)5 57 12 25 56
-----------------------------------
Centre INRA Bordeaux
71, avenue Edouard Bourlaux, CS 20 032
33882 Villenave d'Ornon Cedex
France
Web : Université de Bordeaux<http://www.u-bordeaux.fr/Formation/Composantes-de-formation/IUT-de-l-universite-de-Bordeaux/IUT-site-de-Perigueux>
Web : U<http://www6.bordeaux-aquitaine.inra.fr/bfp>MR Biologie du Fruit et Pathologie<http://www6.bordeaux-aquitaine.inra.fr/bfp>
Web : Plateforme Métabolome<http://www.cgfb.u-bordeaux2.fr/en/metabolome>
________________________________
De : ebouilhol <notifications@github.com>
Envoyé : vendredi 25 novembre 2016 13:37
À : cbib/Plato
Cc : Cecile Cabasson; Author
Objet : Re: [cbib/Plato] Export/Visualization (#19)


Bonjour Cécile,

As-tu de nouvelles infos sur ce que tu avais soulevé plus haut ?

Amicalement,

Emmanuel

-

**Comment by ebouilhol** [comment]
Merci pour cette réponse. Eh bien c'est moi qui espère avoir répondu a ta demande :)
Je clos le sujet, néanmoins si tu as de nouveau des questionnement sur le fonctionnement de la page d'export n'hésite pas !

Amicalement,

Emmanuel
