### ISSUE TITLE
Big sample IDs don't work!

### ISSUE THREAD

**Issue by ygibon** [cbib/Plato#20]
Salut Emmanuel,
Plato me semble marcher de mieux en mieux...
Mais on a eu un petit souci avec des sample IDs issues de codes-barre: il semble y avoir une limite quant au nombre de chiffres saisis. Du coup Plato rabotte sec et rien ne va plus...
A+
y

**Comment by ebouilhol** [comment]
Salut Yves,

Je regarde ça de suite. Peux-tu juste me dire a quel endroit exactement tu rencontre ce problème dans Plato ? (Quel page et quel champ de saisi). Histoire de faire les modification au bon endroit :)

Merci

Emmanuel

**Comment by ygibon** [comment]
Quand on déclare les fresh weights
A+
y

De : ebouilhol [mailto:notifications@github.com]
Envoyé : lundi 21 novembre 2016 11:18
À : cbib/Plato
Cc : Yves Gibon; Author
Objet : Re: [cbib/Plato] Big sample IDs don't work! (#20)


Salut Yves,

Je regarde ça de suite. Peux-tu juste me dire a quel endroit exactement tu rencontre ce problème dans Plato ? (Quel page et quel champ de saisi). Histoire de faire les modification au bon endroit :)

Merci

Emmanuel

**Comment by ebouilhol** [comment]
Merci. 
Aurais-tu un exemple d'ID qui pose problème sous la main ?

Car effectivement il y a plusieurs limites sur l'id d'un sample actuellement : 
- ce doit être un nombre (pas de lettres)
- La taille fixée pour le moment est de 10 chiffres ( ce qui laisse de 0  jusqu'a 9 999 999 999) (je n'imaginais pas qu'il y ai des ID plus grands :))

Je peux le modifier, mais si tu as un exemple je serais sur de faire les bonnes modifications !

Merci !

**Comment by ygibon** [comment]
DRYCE2015-7083020004848-1
D’après la sémantique ExpID-SampleID-AliquotID.
Le sampleID a été généré à partir d’un code-barre. Ici ça donne 13 chiffres mais je ne sais pas si c’est variable !
A+
y


De : ebouilhol [mailto:notifications@github.com]
Envoyé : lundi 21 novembre 2016 11:27
À : cbib/Plato
Cc : Yves Gibon; Author
Objet : Re: [cbib/Plato] Big sample IDs don't work! (#20)


Merci.
Aurais-tu un exemple d'ID qui pose problème sous la main ?

Car effectivement il y a plusieurs limites sur l'id d'un sample actuellement :

  *   ce doit être un nombre (pas de lettres)
  *   La taille fixée pour le moment est de 10 chiffres ( ce qui laisse de 0 jusqu'a 9 999 999 999) (je n'imaginais pas qu'il y ai des ID plus grands :))

Je peux le modifier, mais si tu as un exemple je serais sur de faire les bonnes modifications !

Merci !

**Comment by ebouilhol** [comment]
Merci !

Cela devrait fonctionner maintenant.

N'hésite pas a confirmer ou infirmer !

**Comment by ygibon** [comment]
Excellent, merci!
A+
y

De : ebouilhol [mailto:notifications@github.com]
Envoyé : lundi 21 novembre 2016 12:10
À : cbib/Plato
Cc : Yves Gibon; Author
Objet : Re: [cbib/Plato] Big sample IDs don't work! (#20)


Merci !

Cela devrait fonctionner maintenant.

N'hésite pas a confirmer ou infirmer !
