### ISSUE TITLE
Pb avec fonction "Std & CV"

### ISSUE THREAD

**Issue by ygibon** [cbib/Plato#21]
Hello
on a trouvé un truc bizarre! Onglet export, manipe "Agrauxine", fonction affichage de Std & CV activée, PLATO affiche 140/140 standards pour un des 2 batches (2 - Agrauxine_24112016 - 2016-11-25) et pour un analyte (M03) sur les trois mesurés, alors que cela devrait être 6/6. Les CV affichés sont en revanche corrects. 
A+
y

**Comment by ygibon** [comment]
en fait c'est le batch "1 - Agrauxine_24112016 - 2016-11-25"

**Comment by ebouilhol** [comment]
Hello,

Je suis dessus, j'ai trouvé le pourquoi du problème, je vais essayer de corriger ça rapidement, par contre je n'ai encore aucun indice sur ce qui a pu provoquer cela (les données sont en fait en double dans la base de données, uniquement pour le batch 1 et l'analyte M03 Glucose).

Est-ce que tu sais si il y a eu des manipulations en mode administrateur sur ce batch ? Du genre suppression du batch, puis re-ajout, ou suppression de données puis re-ajout, ou autre ? Cela serait une première piste car les fichiers de log du système ne me donnent pas d'indice.

J'essaye dans un premier temps de remettre les données dans l'ordre. Je te tiens au courant

Emmanuel

**Comment by ebouilhol** [comment]
Le problème est résolu pour le moment. 

Une petite question cependant : Toutes les valeurs dans ces batchs n'ont pas de décimales, est-ce normale ou est-ce anormal ? (Histoire d'être sur :) )

**Comment by ygibon** [comment]
Pas de manipe de ce genre en mode labadmin à ma connaissance. En revanche il semblerait que labdesigner se soit acharné, déclarant et écrasant ce batch un certain nombre de fois, car quelque chose n'allait pas (sans doute des problème d'ID de samples...). Quant aux données sans décimale, ça se produit quand on paramètre le soft du lecteur de microplaque de telle sorte qu'il n'affiche pas de décimales (sans doute, labdesigner a multiplié les delta DO par 1000 et ne souhaitait donc pas voir des décimales inutiles).
A+
y

**Comment by ebouilhol** [comment]
D'accord, merci pour le retour.  Je clos l'incident pour le moment donc.

Est-ce que je pourrais avoir le contact de la personne qui a rentré le batch ? Car si il y a une faille de ce genre il faut que je la trouve plutôt que de risquer de la voir se produire à nouveau. Je pense que si la personne se rappelle un peu des problèmes qu'elle a pu rencontrer ou des comportements étranges de Plato a l'insertion du batch cela pourrait me mettre sur la bonne piste.

Emmanuel

**Comment by ygibon** [comment]
<flavie.metais@hotmail.fr>
A+
y

**Comment by ebouilhol** [comment]
Merci beaucoup !
