### ISSUE TITLE
Données erronées?

### ISSUE THREAD

**Issue by ygibon** [cbib/Plato#23]
Salut Emmanuel, bonne année
gros soucis : les données "export" ne correspondent pas aux données visibles dans "raw data processing".
Voir manip "Dryce", pour le batch "10 - Isabela_DRYCE - 2016-11-15" les valeurs les plus hautes pour Sucrose sont >95000 dans export (données complètement erronées) alors que les processed data sont <100 dans 'raw data processing"! 
Je crois me souvenir que les données brutes ont été enregistrées plusieurs fois, est-il donc possible qu'il y ait un problème de mise à jour ?
Merci pour ton aide...
A+
y

**Comment by ebouilhol** [comment]
Bonjour Yves,

Merci, bonne année également !

Après étude il semble qu'effectivement cette manip souffre des mêmes symptômes que pour le précédent bug. 
Il y à plusieurs données déclarées (288 au lieu de 96). Cela vient sans doute du même problème, il a été résolu depuis normalement, mais les manip qui ont été entrées avant doivent toute avoir le même souci si la personne qui les a rentrées a enregistré plusieurs fois. Je vais donc faire la liste de toutes les manip qui sont touchées et mettre ça au propre au plus vite.

Je te tiens au courant,

Amicalement,

Emmanuel

**Comment by ygibon** [comment]
Merci Emmanuel !
C'est quand même bizarre, c'est une manipe très récente puisqu'elle date de novembre...
A+
Yves

**Comment by ebouilhol** [comment]
Si je me souvient bien, le problème avait été relevé par les batch agrauxine autour du 10 décembre donc il y a malheureusement des chances que les dryce aient été touchés...

**Comment by ygibon** [comment]
OK, c'est rassurant !
A+
y

**Comment by ebouilhol** [comment]
Les erreurs ont été corrigées pour l’expérience DRYCE2015 qui avait effectivement beaucoup de valeurs en double, triples et plus. Il n'est pas impossible que dans le processus de nettoyage, des valeurs qui avaient été exclues ne le soient plus, ce n'est pas une certitude non plus. Les valeurs gardées sont celles qui étaient affichées dans les rawdata.

Je continue de vérifier les autres experiments !

Emmanuel

**Comment by ebouilhol** [comment]
Correction faite, quelques autres batches on écopé du problème : 
scratch-5 pour le M02
scratch-6 pour le M02
S01-1 pour le M05
S02-2 pour le M05

Ils ont été corrigés, les autres batchs sont propres.
